# Generated by Django 3.1.7 on 2021-06-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_produto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='usuario',
            new_name='user',
        ),
    ]
